export const mockEmails = [
  {
    id: "1",
    from: "security-alert@g00gle.com",
    subject: "Urgent: Your Account Has Been Compromised",
    preview:
      "Dear User, We have detected suspicious activity on your account. Please verify your information immediately by clicking the link below...",
    date: "Today, 10:23 AM",
    isRead: false,
    isPhishing: true,
    confidence: 95,
    body: "Dear User,\n\nWe have detected suspicious activity on your account. Please verify your information immediately by clicking the link below to secure your account.\n\nhttp://security-google.com/verify\n\nFailure to verify within 24 hours will result in account suspension.\n\nSincerely,\nGoogle Security Team",
  },
  {
    id: "2",
    from: "newsletter@legitimate-company.com",
    subject: "Your Weekly Newsletter",
    preview: "Check out this week's top stories and updates from our team...",
    date: "Today, 9:15 AM",
    isRead: true,
    isPhishing: false,
    confidence: 98,
  },
  {
    id: "3",
    from: "bank-alert@citib4nk.com",
    subject: "ACTION REQUIRED: Verify Your Recent Transaction",
    preview: "We noticed a suspicious transaction on your account. Please verify this transaction immediately...",
    date: "Yesterday, 4:32 PM",
    isRead: false,
    isPhishing: true,
    confidence: 92,
  },
  {
    id: "4",
    from: "support@microsoft.com",
    subject: "Your Microsoft 365 Subscription",
    preview: "Your subscription will renew on May 15, 2023. Here's what you need to know...",
    date: "Yesterday, 2:45 PM",
    isRead: true,
    isPhishing: false,
    confidence: 99,
  },
  {
    id: "5",
    from: "amazon-shipping@amaz0n-orders.com",
    subject: "Your Amazon Order #12345 Has Shipped",
    preview: "Your recent order has shipped. Click here to track your package...",
    date: "Apr 19, 2023",
    isRead: false,
    isPhishing: true,
    confidence: 88,
  },
  {
    id: "6",
    from: "team@slack.com",
    subject: "New Message in #general",
    preview: "You have a new message from Sarah in the #general channel...",
    date: "Apr 19, 2023",
    isRead: true,
    isPhishing: false,
    confidence: 97,
  },
  {
    id: "7",
    from: "no-reply@dropbox.com",
    subject: "Someone shared a file with you",
    preview: "John Doe has shared a document with you. Click here to view it...",
    date: "Apr 18, 2023",
    isRead: true,
    isPhishing: false,
    confidence: 96,
  },
]
